app:
  name: "NetLinkOld"
  mode: "dev"
  port: 8080
  TokenExpireDuration: 720
  version: "1.0.0"
  apkurl: "https://vkceyugu.cdn.bspapp.com/VKCEYUGU-a933095d-bea3-4928-8f0f-32b5379c7772/e36ae07b-5ef6-4bdb-900f-25a3dd77498a.apk"

log:
  level: "debug"
  filename: "NetLinkOld.log"
  max_size: 200
  max_age: 30
  max_backups: 7


mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root1234"
  dbname: "first"
  max_open_conns: 20
  max_idel_conns: 10

redis:
  host: "127.0.0.1"
  port: "162379"
  db: 0
  password: ""
  max_pool_size: 200

