app:
  name: "NetLinkOld"
  mode: "debug"
  port: 80
  TokenExpireDuration: 720
  version: "2.7"
  apkurl: "https://vkceyugu.cdn.bspapp.com/VKCEYUGU-a933095d-bea3-4928-8f0f-32b5379c7772/e36ae07b-5ef6-4bdb-900f-25a3dd77498a.apk"

log:
  level: "debug"
  filename: "NetLinkOld.log"
  max_size: 200
  max_age: 30
  max_backups: 7


mysql:
  host: ""
  port: 
  user: "1"
  password: "r"
  dbname: "1"
  max_open_conns: 20
  max_idel_conns: 10

redis:
  host: ""
  port: ""
  db: 0
  password: ""
  max_pool_size: 200

tmp:
  audio_path: "D:/Data/GoCode/Upload/temp"
